/* export const countriesData = [
  {
    id: 1,
    translations: {
      de: 'Afghanistan',
      es: 'Afganistán',
      fr: 'Afghanistan',
      en: 'Afghanistan',
      tr: 'Afghanistan',
    },
    latitude: '33.00000000',
    longitude: '65.00000000',
  },
  {
    id: 2,
    translations: {
      de: 'Åland',
      es: 'Alandia',
      fr: 'Åland',
      en: 'Aland Islands',
      tr: 'Aland Islands',
    },
    latitude: '60.11666700',
    longitude: '19.90000000',
  },
  {
    id: 3,
    translations: {
      de: 'Albanien',
      es: 'Albania',
      fr: 'Albanie',
      en: 'Albania',
      tr: 'Albania',
    },
    latitude: '41.00000000',
    longitude: '20.00000000',
  },
  {
    id: 4,
    translations: {
      de: 'Algerien',
      es: 'Argelia',
      fr: 'Algérie',
      en: 'Algeria',
      tr: 'Algeria',
    },
    latitude: '28.00000000',
    longitude: '3.00000000',
  },
  {
    id: 5,
    translations: {
      de: 'Amerikanisch-Samoa',
      es: 'Samoa Americana',
      fr: 'Samoa américaines',
      en: 'American Samoa',
      tr: 'American Samoa',
    },
    latitude: '-14.33333333',
    longitude: '-170.00000000',
  },
  {
    id: 6,
    translations: {
      de: 'Andorra',
      es: 'Andorra',
      fr: 'Andorre',
      en: 'Andorra',
      tr: 'Andorra',
    },
    latitude: '42.50000000',
    longitude: '1.50000000',
  },
  {
    id: 7,
    translations: {
      de: 'Angola',
      es: 'Angola',
      fr: 'Angola',
      en: 'Angola',
      tr: 'Angola',
    },
    latitude: '-12.50000000',
    longitude: '18.50000000',
  },
  {
    id: 8,
    translations: {
      de: 'Anguilla',
      es: 'Anguilla',
      fr: 'Anguilla',
      en: 'Anguilla',
      tr: 'Anguilla',
    },
    latitude: '18.25000000',
    longitude: '-63.16666666',
  },
  {
    id: 9,
    translations: {
      de: 'Antarktika',
      es: 'Antártida',
      fr: 'Antarctique',
      en: 'Antarctica',
      tr: 'Antarctica',
    },
    latitude: '-74.65000000',
    longitude: '4.48000000',
  },
  {
    id: 10,
    translations: {
      de: 'Antigua und Barbuda',
      es: 'Antigua y Barbuda',
      fr: 'Antigua-et-Barbuda',
      en: 'Antigua And Barbuda',
      tr: 'Antigua And Barbuda',
    },
    latitude: '17.05000000',
    longitude: '-61.80000000',
  },
  {
    id: 11,
    translations: {
      de: 'Argentinien',
      es: 'Argentina',
      fr: 'Argentine',
      en: 'Argentina',
      tr: 'Argentina',
    },
    latitude: '-34.00000000',
    longitude: '-64.00000000',
  },
  {
    id: 12,
    translations: {
      de: 'Armenien',
      es: 'Armenia',
      fr: 'Arménie',
      en: 'Armenia',
      tr: 'Armenia',
    },
    latitude: '40.00000000',
    longitude: '45.00000000',
  },
  {
    id: 13,
    translations: {
      de: 'Aruba',
      es: 'Aruba',
      fr: 'Aruba',
      en: 'Aruba',
      tr: 'Aruba',
    },
    latitude: '12.50000000',
    longitude: '-69.96666666',
  },
  {
    id: 14,
    translations: {
      de: 'Australien',
      es: 'Australia',
      fr: 'Australie',
      en: 'Australia',
      tr: 'Australia',
    },
    latitude: '-27.00000000',
    longitude: '133.00000000',
  },
  {
    id: 15,
    translations: {
      de: 'Österreich',
      es: 'Austria',
      fr: 'Autriche',
      en: 'Austria',
      tr: 'Austria',
    },
    latitude: '47.33333333',
    longitude: '13.33333333',
  },
  {
    id: 16,
    translations: {
      de: 'Aserbaidschan',
      es: 'Azerbaiyán',
      fr: 'Azerbaïdjan',
      en: 'Azerbaijan',
      tr: 'Azerbaijan',
    },
    latitude: '40.50000000',
    longitude: '47.50000000',
  },
  {
    id: 17,
    translations: {
      de: 'Bahamas',
      es: 'Bahamas',
      fr: 'Bahamas',
      en: 'Bahamas The',
      tr: 'Bahamas The',
    },
    latitude: '24.25000000',
    longitude: '-76.00000000',
  },
  {
    id: 18,
    translations: {
      de: 'Bahrain',
      es: 'Bahrein',
      fr: 'Bahreïn',
      en: 'Bahrain',
      tr: 'Bahrain',
    },
    latitude: '26.00000000',
    longitude: '50.55000000',
  },
  {
    id: 19,
    translations: {
      de: 'Bangladesch',
      es: 'Bangladesh',
      fr: 'Bangladesh',
      en: 'Bangladesh',
      tr: 'Bangladesh',
    },
    latitude: '24.00000000',
    longitude: '90.00000000',
  },
  {
    id: 20,
    translations: {
      de: 'Barbados',
      es: 'Barbados',
      fr: 'Barbade',
      en: 'Barbados',
      tr: 'Barbados',
    },
    latitude: '13.16666666',
    longitude: '-59.53333333',
  },
  {
    id: 21,
    translations: {
      de: 'Weißrussland',
      es: 'Bielorrusia',
      fr: 'Biélorussie',
      en: 'Belarus',
      tr: 'Belarus',
    },
    latitude: '53.00000000',
    longitude: '28.00000000',
  },
  {
    id: 22,
    translations: {
      de: 'Belgien',
      es: 'Bélgica',
      fr: 'Belgique',
      en: 'Belgium',
      tr: 'Belgium',
    },
    latitude: '50.83333333',
    longitude: '4.00000000',
  },
  {
    id: 23,
    translations: {
      de: 'Belize',
      es: 'Belice',
      fr: 'Belize',
      en: 'Belize',
      tr: 'Belize',
    },
    latitude: '17.25000000',
    longitude: '-88.75000000',
  },
  {
    id: 24,
    translations: {
      de: 'Benin',
      es: 'Benín',
      fr: 'Bénin',
      en: 'Benin',
      tr: 'Benin',
    },
    latitude: '9.50000000',
    longitude: '2.25000000',
  },
  {
    id: 25,
    translations: {
      de: 'Bermuda',
      es: 'Bermudas',
      fr: 'Bermudes',
      en: 'Bermuda',
      tr: 'Bermuda',
    },
    latitude: '32.33333333',
    longitude: '-64.75000000',
  },
  {
    id: 26,
    translations: {
      de: 'Bhutan',
      es: 'Bután',
      fr: 'Bhoutan',
      en: 'Bhutan',
      tr: 'Bhutan',
    },
    latitude: '27.50000000',
    longitude: '90.50000000',
  },
  {
    id: 27,
    translations: {
      de: 'Bolivien',
      es: 'Bolivia',
      fr: 'Bolivie',
      en: 'Bolivia',
      tr: 'Bolivia',
    },
    latitude: '-17.00000000',
    longitude: '-65.00000000',
  },
  {
    id: 155,
    translations: {
      de: 'Bonaire, Sint Eustatius und Saba',
      fr: 'Bonaire, Saint-Eustache et Saba',
      en: 'Bonaire, Sint Eustatius and Saba',
      tr: 'Bonaire, Sint Eustatius and Saba',
    },
    latitude: '12.15000000',
    longitude: '-68.26666700',
  },
  {
    id: 28,
    translations: {
      de: 'Bosnien und Herzegowina',
      es: 'Bosnia y Herzegovina',
      fr: 'Bosnie-Herzégovine',
      en: 'Bosnia and Herzegovina',
      tr: 'Bosnia and Herzegovina',
    },
    latitude: '44.00000000',
    longitude: '18.00000000',
  },
  {
    id: 29,
    translations: {
      de: 'Botswana',
      es: 'Botswana',
      fr: 'Botswana',
      en: 'Botswana',
      tr: 'Botswana',
    },
    latitude: '-22.00000000',
    longitude: '24.00000000',
  },
  {
    id: 30,
    translations: {
      de: 'Bouvetinsel',
      es: 'Isla Bouvet',
      fr: 'Île Bouvet',
      en: 'Bouvet Island',
      tr: 'Bouvet Island',
    },
    latitude: '-54.43333333',
    longitude: '3.40000000',
  },
  {
    id: 31,
    translations: {
      de: 'Brasilien',
      es: 'Brasil',
      fr: 'Brésil',
      en: 'Brazil',
      tr: 'Brazil',
    },
    latitude: '-10.00000000',
    longitude: '-55.00000000',
  },
  {
    id: 32,
    translations: {
      de: 'Britisches Territorium im Indischen Ozean',
      es: 'Territorio Británico del Océano Índico',
      fr: "Territoire britannique de l'océan Indien",
      en: 'British Indian Ocean Territory',
      tr: 'British Indian Ocean Territory',
    },
    latitude: '-6.00000000',
    longitude: '71.50000000',
  },
  {
    id: 33,
    translations: {
      de: 'Brunei',
      es: 'Brunei',
      fr: 'Brunei',
      en: 'Brunei',
      tr: 'Brunei',
    },
    latitude: '4.50000000',
    longitude: '114.66666666',
  },
  {
    id: 34,
    translations: {
      de: 'Bulgarien',
      es: 'Bulgaria',
      fr: 'Bulgarie',
      en: 'Bulgaria',
      tr: 'Bulgaria',
    },
    latitude: '43.00000000',
    longitude: '25.00000000',
  },
  {
    id: 35,
    translations: {
      de: 'Burkina Faso',
      es: 'Burkina Faso',
      fr: 'Burkina Faso',
      en: 'Burkina Faso',
      tr: 'Burkina Faso',
    },
    latitude: '13.00000000',
    longitude: '-2.00000000',
  },
  {
    id: 36,
    translations: {
      de: 'Burundi',
      es: 'Burundi',
      fr: 'Burundi',
      en: 'Burundi',
      tr: 'Burundi',
    },
    latitude: '-3.50000000',
    longitude: '30.00000000',
  },
  {
    id: 37,
    translations: {
      de: 'Kambodscha',
      es: 'Camboya',
      fr: 'Cambodge',
      en: 'Cambodia',
      tr: 'Cambodia',
    },
    latitude: '13.00000000',
    longitude: '105.00000000',
  },
  {
    id: 38,
    translations: {
      de: 'Kamerun',
      es: 'Camerún',
      fr: 'Cameroun',
      en: 'Cameroon',
      tr: 'Cameroon',
    },
    latitude: '6.00000000',
    longitude: '12.00000000',
  },
  {
    id: 39,
    translations: {
      de: 'Kanada',
      es: 'Canadá',
      fr: 'Canada',
      en: 'Canada',
      tr: 'Canada',
    },
    latitude: '60.00000000',
    longitude: '-95.00000000',
  },
  {
    id: 40,
    translations: {
      de: 'Kap Verde',
      es: 'Cabo Verde',
      fr: 'Cap Vert',
      en: 'Cape Verde',
      tr: 'Cape Verde',
    },
    latitude: '16.00000000',
    longitude: '-24.00000000',
  },
  {
    id: 41,
    translations: {
      de: 'Kaimaninseln',
      es: 'Islas Caimán',
      fr: 'Îles Caïmans',
      en: 'Cayman Islands',
      tr: 'Cayman Islands',
    },
    latitude: '19.50000000',
    longitude: '-80.50000000',
  },
  {
    id: 42,
    translations: {
      de: 'Zentralafrikanische Republik',
      es: 'República Centroafricana',
      fr: 'République centrafricaine',
      en: 'Central African Republic',
      tr: 'Central African Republic',
    },
    latitude: '7.00000000',
    longitude: '21.00000000',
  },
  {
    id: 43,
    translations: {
      de: 'Tschad',
      es: 'Chad',
      fr: 'Tchad',
      en: 'Chad',
      tr: 'Chad',
    },
    latitude: '15.00000000',
    longitude: '19.00000000',
  },
  {
    id: 44,
    translations: {
      de: 'Chile',
      es: 'Chile',
      fr: 'Chili',
      en: 'Chile',
      tr: 'Chile',
    },
    latitude: '-30.00000000',
    longitude: '-71.00000000',
  },
  {
    id: 45,
    translations: {
      de: 'China',
      es: 'China',
      fr: 'Chine',
      en: 'China',
      tr: 'China',
    },
    latitude: '35.00000000',
    longitude: '105.00000000',
  },
  {
    id: 46,
    translations: {
      de: 'Weihnachtsinsel',
      es: 'Isla de Navidad',
      fr: 'Île Christmas',
      en: 'Christmas Island',
      tr: 'Christmas Island',
    },
    latitude: '-10.50000000',
    longitude: '105.66666666',
  },
  {
    id: 47,
    translations: {
      de: 'Kokosinseln',
      es: 'Islas Cocos o Islas Keeling',
      fr: 'Îles Cocos',
      en: 'Cocos (Keeling) Islands',
      tr: 'Cocos (Keeling) Islands',
    },
    latitude: '-12.50000000',
    longitude: '96.83333333',
  },
  {
    id: 48,
    translations: {
      de: 'Kolumbien',
      es: 'Colombia',
      fr: 'Colombie',
      en: 'Colombia',
      tr: 'Colombia',
    },
    latitude: '4.00000000',
    longitude: '-72.00000000',
  },
  {
    id: 49,
    translations: {
      de: 'Union der Komoren',
      es: 'Comoras',
      fr: 'Comores',
      en: 'Comoros',
      tr: 'Comoros',
    },
    latitude: '-12.16666666',
    longitude: '44.25000000',
  },
  {
    id: 50,
    translations: {
      de: 'Kongo',
      es: 'Congo',
      fr: 'Congo',
      en: 'Congo',
      tr: 'Congo',
    },
    latitude: '-1.00000000',
    longitude: '15.00000000',
  },
  {
    id: 51,
    translations: {
      de: 'Kongo (Dem. Rep.)',
      es: 'Congo (Rep. Dem.)',
      fr: 'Congo (Rép. dém.)',
      en: 'Congo The Democratic Republic Of The',
      tr: 'Congo The Democratic Republic Of The',
    },
    latitude: '0.00000000',
    longitude: '25.00000000',
  },
  {
    id: 52,
    translations: {
      de: 'Cookinseln',
      es: 'Islas Cook',
      fr: 'Îles Cook',
      en: 'Cook Islands',
      tr: 'Cook Islands',
    },
    latitude: '-21.23333333',
    longitude: '-159.76666666',
  },
  {
    id: 53,
    translations: {
      de: 'Costa Rica',
      es: 'Costa Rica',
      fr: 'Costa Rica',
      en: 'Costa Rica',
      tr: 'Costa Rica',
    },
    latitude: '10.00000000',
    longitude: '-84.00000000',
  },
  {
    id: 54,
    translations: {
      de: 'Elfenbeinküste',
      es: 'Costa de Marfil',
      fr: "Côte d'Ivoire",
      en: "Cote D'Ivoire (Ivory Coast)",
      tr: "Cote D'Ivoire (Ivory Coast)",
    },
    latitude: '8.00000000',
    longitude: '-5.00000000',
  },
  {
    id: 55,
    translations: {
      de: 'Kroatien',
      es: 'Croacia',
      fr: 'Croatie',
      en: 'Croatia (Hrvatska)',
      tr: 'Croatia (Hrvatska)',
    },
    latitude: '45.16666666',
    longitude: '15.50000000',
  },
  {
    id: 56,
    translations: {
      de: 'Kuba',
      es: 'Cuba',
      fr: 'Cuba',
      en: 'Cuba',
      tr: 'Cuba',
    },
    latitude: '21.50000000',
    longitude: '-80.00000000',
  },
  {
    id: 249,
    translations: {
      de: 'Curaçao',
      fr: 'Curaçao',
      en: 'Curaçao',
      tr: 'Curaçao',
    },
    latitude: '12.11666700',
    longitude: '-68.93333300',
  },
  {
    id: 57,
    translations: {
      de: 'Zypern',
      es: 'Chipre',
      fr: 'Chypre',
      en: 'Cyprus',
      tr: 'Cyprus',
    },
    latitude: '35.00000000',
    longitude: '33.00000000',
  },
  {
    id: 58,
    translations: {
      de: 'Tschechische Republik',
      es: 'República Checa',
      fr: 'République tchèque',
      en: 'Czech Republic',
      tr: 'Czech Republic',
    },
    latitude: '49.75000000',
    longitude: '15.50000000',
  },
  {
    id: 59,
    translations: {
      de: 'Dänemark',
      es: 'Dinamarca',
      fr: 'Danemark',
      en: 'Denmark',
      tr: 'Denmark',
    },
    latitude: '56.00000000',
    longitude: '10.00000000',
  },
  {
    id: 60,
    translations: {
      de: 'Dschibuti',
      es: 'Yibuti',
      fr: 'Djibouti',
      en: 'Djibouti',
      tr: 'Djibouti',
    },
    latitude: '11.50000000',
    longitude: '43.00000000',
  },
  {
    id: 61,
    translations: {
      de: 'Dominica',
      es: 'Dominica',
      fr: 'Dominique',
      en: 'Dominica',
      tr: 'Dominica',
    },
    latitude: '15.41666666',
    longitude: '-61.33333333',
  },
  {
    id: 62,
    translations: {
      de: 'Dominikanische Republik',
      es: 'República Dominicana',
      fr: 'République dominicaine',
      en: 'Dominican Republic',
      tr: 'Dominican Republic',
    },
    latitude: '19.00000000',
    longitude: '-70.66666666',
  },
  {
    id: 63,
    translations: {
      de: 'Timor-Leste',
      es: 'Timor Oriental',
      fr: 'Timor oriental',
      en: 'East Timor',
      tr: 'East Timor',
    },
    latitude: '-8.83333333',
    longitude: '125.91666666',
  },
  {
    id: 64,
    translations: {
      de: 'Ecuador',
      es: 'Ecuador',
      fr: 'Équateur',
      en: 'Ecuador',
      tr: 'Ecuador',
    },
    latitude: '-2.00000000',
    longitude: '-77.50000000',
  },
  {
    id: 65,
    translations: {
      de: 'Ägypten',
      es: 'Egipto',
      fr: 'Égypte',
      en: 'Egypt',
      tr: 'Egypt',
    },
    latitude: '27.00000000',
    longitude: '30.00000000',
  },
  {
    id: 66,
    translations: {
      de: 'El Salvador',
      es: 'El Salvador',
      fr: 'Salvador',
      en: 'El Salvador',
      tr: 'El Salvador',
    },
    latitude: '13.83333333',
    longitude: '-88.91666666',
  },
  {
    id: 67,
    translations: {
      de: 'Äquatorial-Guinea',
      es: 'Guinea Ecuatorial',
      fr: 'Guinée-Équatoriale',
      en: 'Equatorial Guinea',
      tr: 'Equatorial Guinea',
    },
    latitude: '2.00000000',
    longitude: '10.00000000',
  },
  {
    id: 68,
    translations: {
      de: 'Eritrea',
      es: 'Eritrea',
      fr: 'Érythrée',
      en: 'Eritrea',
      tr: 'Eritrea',
    },
    latitude: '15.00000000',
    longitude: '39.00000000',
  },
  {
    id: 69,
    translations: {
      de: 'Estland',
      es: 'Estonia',
      fr: 'Estonie',
      en: 'Estonia',
      tr: 'Estonia',
    },
    latitude: '59.00000000',
    longitude: '26.00000000',
  },
  {
    id: 70,
    translations: {
      de: 'Äthiopien',
      es: 'Etiopía',
      fr: 'Éthiopie',
      en: 'Ethiopia',
      tr: 'Ethiopia',
    },
    latitude: '8.00000000',
    longitude: '38.00000000',
  },
  {
    id: 71,
    translations: {
      de: 'Falklandinseln',
      es: 'Islas Malvinas',
      fr: 'Îles Malouines',
      en: 'Falkland Islands',
      tr: 'Falkland Islands',
    },
    latitude: '-51.75000000',
    longitude: '-59.00000000',
  },
  {
    id: 72,
    translations: {
      de: 'Färöer-Inseln',
      es: 'Islas Faroe',
      fr: 'Îles Féroé',
      en: 'Faroe Islands',
      tr: 'Faroe Islands',
    },
    latitude: '62.00000000',
    longitude: '-7.00000000',
  },
  {
    id: 73,
    translations: {
      de: 'Fidschi',
      es: 'Fiyi',
      fr: 'Fidji',
      en: 'Fiji Islands',
      tr: 'Fiji Islands',
    },
    latitude: '-18.00000000',
    longitude: '175.00000000',
  },
  {
    id: 74,
    translations: {
      de: 'Finnland',
      es: 'Finlandia',
      fr: 'Finlande',
      en: 'Finland',
      tr: 'Finland',
    },
    latitude: '64.00000000',
    longitude: '26.00000000',
  },
  {
    id: 75,
    translations: {
      de: 'Frankreich',
      es: 'Francia',
      fr: 'France',
      en: 'France',
      tr: 'France',
    },
    latitude: '46.00000000',
    longitude: '2.00000000',
  },
  {
    id: 76,
    translations: {
      de: 'Französisch Guyana',
      es: 'Guayana Francesa',
      fr: 'Guayane',
      en: 'French Guiana',
      tr: 'French Guiana',
    },
    latitude: '4.00000000',
    longitude: '-53.00000000',
  },
  {
    id: 77,
    translations: {
      de: 'Französisch-Polynesien',
      es: 'Polinesia Francesa',
      fr: 'Polynésie française',
      en: 'French Polynesia',
      tr: 'French Polynesia',
    },
    latitude: '-15.00000000',
    longitude: '-140.00000000',
  },
  {
    id: 78,
    translations: {
      de: 'Französische Süd- und Antarktisgebiete',
      es: 'Tierras Australes y Antárticas Francesas',
      fr: 'Terres australes et antarctiques françaises',
      en: 'French Southern Territories',
      tr: 'French Southern Territories',
    },
    latitude: '-49.25000000',
    longitude: '69.16700000',
  },
  {
    id: 79,
    translations: {
      de: 'Gabun',
      es: 'Gabón',
      fr: 'Gabon',
      en: 'Gabon',
      tr: 'Gabon',
    },
    latitude: '-1.00000000',
    longitude: '11.75000000',
  },
  {
    id: 80,
    translations: {
      de: 'Gambia',
      es: 'Gambia',
      fr: 'Gambie',
      en: 'Gambia The',
      tr: 'Gambia The',
    },
    latitude: '13.46666666',
    longitude: '-16.56666666',
  },
  {
    id: 81,
    translations: {
      de: 'Georgien',
      es: 'Georgia',
      fr: 'Géorgie',
      en: 'Georgia',
      tr: 'Georgia',
    },
    latitude: '42.00000000',
    longitude: '43.50000000',
  },
  {
    id: 82,
    translations: {
      de: 'Deutschland',
      es: 'Alemania',
      fr: 'Allemagne',
      en: 'Germany',
      tr: 'Germany',
    },
    latitude: '51.00000000',
    longitude: '9.00000000',
  },
  {
    id: 83,
    translations: {
      de: 'Ghana',
      es: 'Ghana',
      fr: 'Ghana',
      en: 'Ghana',
      tr: 'Ghana',
    },
    latitude: '8.00000000',
    longitude: '-2.00000000',
  },
  {
    id: 84,
    translations: {
      de: 'Gibraltar',
      es: 'Gibraltar',
      fr: 'Gibraltar',
      en: 'Gibraltar',
      tr: 'Gibraltar',
    },
    latitude: '36.13333333',
    longitude: '-5.35000000',
  },
  {
    id: 85,
    translations: {
      de: 'Griechenland',
      es: 'Grecia',
      fr: 'Grèce',
      en: 'Greece',
      tr: 'Greece',
    },
    latitude: '39.00000000',
    longitude: '22.00000000',
  },
  {
    id: 86,
    translations: {
      de: 'Grönland',
      es: 'Groenlandia',
      fr: 'Groenland',
      en: 'Greenland',
      tr: 'Greenland',
    },
    latitude: '72.00000000',
    longitude: '-40.00000000',
  },
  {
    id: 87,
    translations: {
      de: 'Grenada',
      es: 'Grenada',
      fr: 'Grenade',
      en: 'Grenada',
      tr: 'Grenada',
    },
    latitude: '12.11666666',
    longitude: '-61.66666666',
  },
  {
    id: 88,
    translations: {
      de: 'Guadeloupe',
      es: 'Guadalupe',
      fr: 'Guadeloupe',
      en: 'Guadeloupe',
      tr: 'Guadeloupe',
    },
    latitude: '16.25000000',
    longitude: '-61.58333300',
  },
  {
    id: 89,
    translations: {
      de: 'Guam',
      es: 'Guam',
      fr: 'Guam',
      en: 'Guam',
      tr: 'Guam',
    },
    latitude: '13.46666666',
    longitude: '144.78333333',
  },
  {
    id: 90,
    translations: {
      de: 'Guatemala',
      es: 'Guatemala',
      fr: 'Guatemala',
      en: 'Guatemala',
      tr: 'Guatemala',
    },
    latitude: '15.50000000',
    longitude: '-90.25000000',
  },
  {
    id: 91,
    translations: {
      de: 'Guernsey',
      es: 'Guernsey',
      fr: 'Guernesey',
      en: 'Guernsey and Alderney',
      tr: 'Guernsey and Alderney',
    },
    latitude: '49.46666666',
    longitude: '-2.58333333',
  },
  {
    id: 92,
    translations: {
      de: 'Guinea',
      es: 'Guinea',
      fr: 'Guinée',
      en: 'Guinea',
      tr: 'Guinea',
    },
    latitude: '11.00000000',
    longitude: '-10.00000000',
  },
  {
    id: 93,
    translations: {
      de: 'Guinea-Bissau',
      es: 'Guinea-Bisáu',
      fr: 'Guinée-Bissau',
      en: 'Guinea-Bissau',
      tr: 'Guinea-Bissau',
    },
    latitude: '12.00000000',
    longitude: '-15.00000000',
  },
  {
    id: 94,
    translations: {
      de: 'Guyana',
      es: 'Guyana',
      fr: 'Guyane',
      en: 'Guyana',
      tr: 'Guyana',
    },
    latitude: '5.00000000',
    longitude: '-59.00000000',
  },
  {
    id: 95,
    translations: {
      de: 'Haiti',
      es: 'Haiti',
      fr: 'Haïti',
      en: 'Haiti',
      tr: 'Haiti',
    },
    latitude: '19.00000000',
    longitude: '-72.41666666',
  },
  {
    id: 96,
    translations: {
      de: 'Heard und die McDonaldinseln',
      es: 'Islas Heard y McDonald',
      fr: 'Îles Heard-et-MacDonald',
      en: 'Heard Island and McDonald Islands',
      tr: 'Heard Island and McDonald Islands',
    },
    latitude: '-53.10000000',
    longitude: '72.51666666',
  },
  {
    id: 97,
    translations: {
      de: 'Honduras',
      es: 'Honduras',
      fr: 'Honduras',
      en: 'Honduras',
      tr: 'Honduras',
    },
    latitude: '15.00000000',
    longitude: '-86.50000000',
  },
  {
    id: 98,
    translations: {
      de: 'Hong Kong',
      es: 'Hong Kong',
      fr: 'Hong Kong',
      en: 'Hong Kong S.A.R.',
      tr: 'Hong Kong S.A.R.',
    },
    latitude: '22.25000000',
    longitude: '114.16666666',
  },
  {
    id: 99,
    translations: {
      de: 'Ungarn',
      es: 'Hungría',
      fr: 'Hongrie',
      en: 'Hungary',
      tr: 'Hungary',
    },
    latitude: '47.00000000',
    longitude: '20.00000000',
  },
  {
    id: 100,
    translations: {
      de: 'Island',
      es: 'Islandia',
      fr: 'Islande',
      en: 'Iceland',
      tr: 'Iceland',
    },
    latitude: '65.00000000',
    longitude: '-18.00000000',
  },
  {
    id: 101,
    translations: {
      de: 'Indien',
      es: 'India',
      fr: 'Inde',
      en: 'India',
      tr: 'India',
    },
    latitude: '20.00000000',
    longitude: '77.00000000',
  },
  {
    id: 102,
    translations: {
      de: 'Indonesien',
      es: 'Indonesia',
      fr: 'Indonésie',
      en: 'Indonesia',
      tr: 'Indonesia',
    },
    latitude: '-5.00000000',
    longitude: '120.00000000',
  },
  {
    id: 103,
    translations: {
      de: 'Iran',
      es: 'Iran',
      fr: 'Iran',
      en: 'Iran',
      tr: 'Iran',
    },
    latitude: '32.00000000',
    longitude: '53.00000000',
  },
  {
    id: 104,
    translations: {
      de: 'Irak',
      es: 'Irak',
      fr: 'Irak',
      en: 'Iraq',
      tr: 'Iraq',
    },
    latitude: '33.00000000',
    longitude: '44.00000000',
  },
  {
    id: 105,
    translations: {
      de: 'Irland',
      es: 'Irlanda',
      fr: 'Irlande',
      en: 'Ireland',
      tr: 'Ireland',
    },
    latitude: '53.00000000',
    longitude: '-8.00000000',
  },
  {
    id: 106,
    translations: {
      de: 'Israel',
      es: 'Israel',
      fr: 'Israël',
      en: 'Israel',
      tr: 'Israel',
    },
    latitude: '31.50000000',
    longitude: '34.75000000',
  },
  {
    id: 107,
    translations: {
      de: 'Italien',
      es: 'Italia',
      fr: 'Italie',
      en: 'Italy',
      tr: 'Italy',
    },
    latitude: '42.83333333',
    longitude: '12.83333333',
  },
  {
    id: 108,
    translations: {
      de: 'Jamaika',
      es: 'Jamaica',
      fr: 'Jamaïque',
      en: 'Jamaica',
      tr: 'Jamaica',
    },
    latitude: '18.25000000',
    longitude: '-77.50000000',
  },
  {
    id: 109,
    translations: {
      de: 'Japan',
      es: 'Japón',
      fr: 'Japon',
      en: 'Japan',
      tr: 'Japan',
    },
    latitude: '36.00000000',
    longitude: '138.00000000',
  },
  {
    id: 110,
    translations: {
      de: 'Jersey',
      es: 'Jersey',
      fr: 'Jersey',
      en: 'Jersey',
      tr: 'Jersey',
    },
    latitude: '49.25000000',
    longitude: '-2.16666666',
  },
  {
    id: 111,
    translations: {
      de: 'Jordanien',
      es: 'Jordania',
      fr: 'Jordanie',
      en: 'Jordan',
      tr: 'Jordan',
    },
    latitude: '31.00000000',
    longitude: '36.00000000',
  },
  {
    id: 112,
    translations: {
      de: 'Kasachstan',
      es: 'Kazajistán',
      fr: 'Kazakhstan',
      en: 'Kazakhstan',
      tr: 'Kazakhstan',
    },
    latitude: '48.00000000',
    longitude: '68.00000000',
  },
  {
    id: 113,
    translations: {
      de: 'Kenia',
      es: 'Kenia',
      fr: 'Kenya',
      en: 'Kenya',
      tr: 'Kenya',
    },
    latitude: '1.00000000',
    longitude: '38.00000000',
  },
  {
    id: 114,
    translations: {
      de: 'Kiribati',
      es: 'Kiribati',
      fr: 'Kiribati',
      en: 'Kiribati',
      tr: 'Kiribati',
    },
    latitude: '1.41666666',
    longitude: '173.00000000',
  },
  {
    id: 115,
    translations: {
      de: 'Nordkorea',
      es: 'Corea del Norte',
      fr: 'Corée du Nord',
      en: 'Korea North',
      tr: 'Korea North',
    },
    latitude: '40.00000000',
    longitude: '127.00000000',
  },
  {
    id: 116,
    translations: {
      de: 'Südkorea',
      es: 'Corea del Sur',
      fr: 'Corée du Sud',
      en: 'Korea South',
      tr: 'Korea South',
    },
    latitude: '37.00000000',
    longitude: '127.50000000',
  },
  {
    id: 248,
    translations: {
      en: 'Kosovo',
      tr: 'Kosovo',
    },
    latitude: '42.56129090',
    longitude: '20.34030350',
  },
  {
    id: 117,
    translations: {
      de: 'Kuwait',
      es: 'Kuwait',
      fr: 'Koweït',
      en: 'Kuwait',
      tr: 'Kuwait',
    },
    latitude: '29.50000000',
    longitude: '45.75000000',
  },
  {
    id: 118,
    translations: {
      de: 'Kirgisistan',
      es: 'Kirguizistán',
      fr: 'Kirghizistan',
      en: 'Kyrgyzstan',
      tr: 'Kyrgyzstan',
    },
    latitude: '41.00000000',
    longitude: '75.00000000',
  },
  {
    id: 119,
    translations: {
      de: 'Laos',
      es: 'Laos',
      fr: 'Laos',
      en: 'Laos',
      tr: 'Laos',
    },
    latitude: '18.00000000',
    longitude: '105.00000000',
  },
  {
    id: 120,
    translations: {
      de: 'Lettland',
      es: 'Letonia',
      fr: 'Lettonie',
      en: 'Latvia',
      tr: 'Latvia',
    },
    latitude: '57.00000000',
    longitude: '25.00000000',
  },
  {
    id: 121,
    translations: {
      de: 'Libanon',
      es: 'Líbano',
      fr: 'Liban',
      en: 'Lebanon',
      tr: 'Lebanon',
    },
    latitude: '33.83333333',
    longitude: '35.83333333',
  },
  {
    id: 122,
    translations: {
      de: 'Lesotho',
      es: 'Lesotho',
      fr: 'Lesotho',
      en: 'Lesotho',
      tr: 'Lesotho',
    },
    latitude: '-29.50000000',
    longitude: '28.50000000',
  },
  {
    id: 123,
    translations: {
      de: 'Liberia',
      es: 'Liberia',
      fr: 'Liberia',
      en: 'Liberia',
      tr: 'Liberia',
    },
    latitude: '6.50000000',
    longitude: '-9.50000000',
  },
  {
    id: 124,
    translations: {
      de: 'Libyen',
      es: 'Libia',
      fr: 'Libye',
      en: 'Libya',
      tr: 'Libya',
    },
    latitude: '25.00000000',
    longitude: '17.00000000',
  },
  {
    id: 125,
    translations: {
      de: 'Liechtenstein',
      es: 'Liechtenstein',
      fr: 'Liechtenstein',
      en: 'Liechtenstein',
      tr: 'Liechtenstein',
    },
    latitude: '47.26666666',
    longitude: '9.53333333',
  },
  {
    id: 126,
    translations: {
      de: 'Litauen',
      es: 'Lituania',
      fr: 'Lituanie',
      en: 'Lithuania',
      tr: 'Lithuania',
    },
    latitude: '56.00000000',
    longitude: '24.00000000',
  },
  {
    id: 127,
    translations: {
      de: 'Luxemburg',
      es: 'Luxemburgo',
      fr: 'Luxembourg',
      en: 'Luxembourg',
      tr: 'Luxembourg',
    },
    latitude: '49.75000000',
    longitude: '6.16666666',
  },
  {
    id: 128,
    translations: {
      de: 'Macao',
      es: 'Macao',
      fr: 'Macao',
      en: 'Macau S.A.R.',
      tr: 'Macau S.A.R.',
    },
    latitude: '22.16666666',
    longitude: '113.55000000',
  },
  {
    id: 129,
    translations: {
      de: 'Mazedonien',
      es: 'Macedonia',
      fr: 'Macédoine',
      en: 'Macedonia',
      tr: 'Macedonia',
    },
    latitude: '41.83333333',
    longitude: '22.00000000',
  },
  {
    id: 130,
    translations: {
      de: 'Madagaskar',
      es: 'Madagascar',
      fr: 'Madagascar',
      en: 'Madagascar',
      tr: 'Madagascar',
    },
    latitude: '-20.00000000',
    longitude: '47.00000000',
  },
  {
    id: 131,
    translations: {
      de: 'Malawi',
      es: 'Malawi',
      fr: 'Malawi',
      en: 'Malawi',
      tr: 'Malawi',
    },
    latitude: '-13.50000000',
    longitude: '34.00000000',
  },
  {
    id: 132,
    translations: {
      de: 'Malaysia',
      es: 'Malasia',
      fr: 'Malaisie',
      en: 'Malaysia',
      tr: 'Malaysia',
    },
    latitude: '2.50000000',
    longitude: '112.50000000',
  },
  {
    id: 133,
    translations: {
      de: 'Malediven',
      es: 'Maldivas',
      fr: 'Maldives',
      en: 'Maldives',
      tr: 'Maldives',
    },
    latitude: '3.25000000',
    longitude: '73.00000000',
  },
  {
    id: 134,
    translations: {
      de: 'Mali',
      es: 'Mali',
      fr: 'Mali',
      en: 'Mali',
      tr: 'Mali',
    },
    latitude: '17.00000000',
    longitude: '-4.00000000',
  },
  {
    id: 135,
    translations: {
      de: 'Malta',
      es: 'Malta',
      fr: 'Malte',
      en: 'Malta',
      tr: 'Malta',
    },
    latitude: '35.83333333',
    longitude: '14.58333333',
  },
  {
    id: 136,
    translations: {
      de: 'Insel Man',
      es: 'Isla de Man',
      fr: 'Île de Man',
      en: 'Man (Isle of)',
      tr: 'Man (Isle of)',
    },
    latitude: '54.25000000',
    longitude: '-4.50000000',
  },
  {
    id: 137,
    translations: {
      de: 'Marshallinseln',
      es: 'Islas Marshall',
      fr: 'Îles Marshall',
      en: 'Marshall Islands',
      tr: 'Marshall Islands',
    },
    latitude: '9.00000000',
    longitude: '168.00000000',
  },
  {
    id: 138,
    translations: {
      de: 'Martinique',
      es: 'Martinica',
      fr: 'Martinique',
      en: 'Martinique',
      tr: 'Martinique',
    },
    latitude: '14.66666700',
    longitude: '-61.00000000',
  },
  {
    id: 139,
    translations: {
      de: 'Mauretanien',
      es: 'Mauritania',
      fr: 'Mauritanie',
      en: 'Mauritania',
      tr: 'Mauritania',
    },
    latitude: '20.00000000',
    longitude: '-12.00000000',
  },
  {
    id: 140,
    translations: {
      de: 'Mauritius',
      es: 'Mauricio',
      fr: 'Île Maurice',
      en: 'Mauritius',
      tr: 'Mauritius',
    },
    latitude: '-20.28333333',
    longitude: '57.55000000',
  },
  {
    id: 141,
    translations: {
      de: 'Mayotte',
      es: 'Mayotte',
      fr: 'Mayotte',
      en: 'Mayotte',
      tr: 'Mayotte',
    },
    latitude: '-12.83333333',
    longitude: '45.16666666',
  },
  {
    id: 142,
    translations: {
      de: 'Mexiko',
      es: 'México',
      fr: 'Mexique',
      en: 'Mexico',
      tr: 'Mexico',
    },
    latitude: '23.00000000',
    longitude: '-102.00000000',
  },
  {
    id: 143,
    translations: {
      de: 'Mikronesien',
      es: 'Micronesia',
      fr: 'Micronésie',
      en: 'Micronesia',
      tr: 'Micronesia',
    },
    latitude: '6.91666666',
    longitude: '158.25000000',
  },
  {
    id: 144,
    translations: {
      de: 'Moldawie',
      es: 'Moldavia',
      fr: 'Moldavie',
      en: 'Moldova',
      tr: 'Moldova',
    },
    latitude: '47.00000000',
    longitude: '29.00000000',
  },
  {
    id: 145,
    translations: {
      de: 'Monaco',
      es: 'Mónaco',
      fr: 'Monaco',
      en: 'Monaco',
      tr: 'Monaco',
    },
    latitude: '43.73333333',
    longitude: '7.40000000',
  },
  {
    id: 146,
    translations: {
      de: 'Mongolei',
      es: 'Mongolia',
      fr: 'Mongolie',
      en: 'Mongolia',
      tr: 'Mongolia',
    },
    latitude: '46.00000000',
    longitude: '105.00000000',
  },
  {
    id: 147,
    translations: {
      de: 'Montenegro',
      es: 'Montenegro',
      fr: 'Monténégro',
      en: 'Montenegro',
      tr: 'Montenegro',
    },
    latitude: '42.50000000',
    longitude: '19.30000000',
  },
  {
    id: 148,
    translations: {
      de: 'Montserrat',
      es: 'Montserrat',
      fr: 'Montserrat',
      en: 'Montserrat',
      tr: 'Montserrat',
    },
    latitude: '16.75000000',
    longitude: '-62.20000000',
  },
  {
    id: 149,
    translations: {
      de: 'Marokko',
      es: 'Marruecos',
      fr: 'Maroc',
      en: 'Morocco',
      tr: 'Morocco',
    },
    latitude: '32.00000000',
    longitude: '-5.00000000',
  },
  {
    id: 150,
    translations: {
      de: 'Mosambik',
      es: 'Mozambique',
      fr: 'Mozambique',
      en: 'Mozambique',
      tr: 'Mozambique',
    },
    latitude: '-18.25000000',
    longitude: '35.00000000',
  },
  {
    id: 151,
    translations: {
      de: 'Myanmar',
      es: 'Myanmar',
      fr: 'Myanmar',
      en: 'Myanmar',
      tr: 'Myanmar',
    },
    latitude: '22.00000000',
    longitude: '98.00000000',
  },
  {
    id: 152,
    translations: {
      de: 'Namibia',
      es: 'Namibia',
      fr: 'Namibie',
      en: 'Namibia',
      tr: 'Namibia',
    },
    latitude: '-22.00000000',
    longitude: '17.00000000',
  },
  {
    id: 153,
    translations: {
      de: 'Nauru',
      es: 'Nauru',
      fr: 'Nauru',
      en: 'Nauru',
      tr: 'Nauru',
    },
    latitude: '-0.53333333',
    longitude: '166.91666666',
  },
  {
    id: 154,
    translations: {
      de: 'Népal',
      es: 'Nepal',
      fr: 'Népal',
      en: 'Nepal',
      tr: 'Nepal',
    },
    latitude: '28.00000000',
    longitude: '84.00000000',
  },
  {
    id: 156,
    translations: {
      de: 'Niederlande',
      es: 'Países Bajos',
      fr: 'Pays-Bas',
      en: 'Netherlands The',
      tr: 'Netherlands The',
    },
    latitude: '52.50000000',
    longitude: '5.75000000',
  },
  {
    id: 157,
    translations: {
      de: 'Neukaledonien',
      es: 'Nueva Caledonia',
      fr: 'Nouvelle-Calédonie',
      en: 'New Caledonia',
      tr: 'New Caledonia',
    },
    latitude: '-21.50000000',
    longitude: '165.50000000',
  },
  {
    id: 158,
    translations: {
      de: 'Neuseeland',
      es: 'Nueva Zelanda',
      fr: 'Nouvelle-Zélande',
      en: 'New Zealand',
      tr: 'New Zealand',
    },
    latitude: '-41.00000000',
    longitude: '174.00000000',
  },
  {
    id: 159,
    translations: {
      de: 'Nicaragua',
      es: 'Nicaragua',
      fr: 'Nicaragua',
      en: 'Nicaragua',
      tr: 'Nicaragua',
    },
    latitude: '13.00000000',
    longitude: '-85.00000000',
  },
  {
    id: 160,
    translations: {
      de: 'Niger',
      es: 'Níger',
      fr: 'Niger',
      en: 'Niger',
      tr: 'Niger',
    },
    latitude: '16.00000000',
    longitude: '8.00000000',
  },
  {
    id: 161,
    translations: {
      de: 'Nigeria',
      es: 'Nigeria',
      fr: 'Nigéria',
      en: 'Nigeria',
      tr: 'Nigeria',
    },
    latitude: '10.00000000',
    longitude: '8.00000000',
  },
  {
    id: 162,
    translations: {
      de: 'Niue',
      es: 'Niue',
      fr: 'Niue',
      en: 'Niue',
      tr: 'Niue',
    },
    latitude: '-19.03333333',
    longitude: '-169.86666666',
  },
  {
    id: 163,
    translations: {
      de: 'Norfolkinsel',
      es: 'Isla de Norfolk',
      fr: 'Île de Norfolk',
      en: 'Norfolk Island',
      tr: 'Norfolk Island',
    },
    latitude: '-29.03333333',
    longitude: '167.95000000',
  },
  {
    id: 164,
    translations: {
      de: 'Nördliche Marianen',
      es: 'Islas Marianas del Norte',
      fr: 'Îles Mariannes du Nord',
      en: 'Northern Mariana Islands',
      tr: 'Northern Mariana Islands',
    },
    latitude: '15.20000000',
    longitude: '145.75000000',
  },
  {
    id: 165,
    translations: {
      de: 'Norwegen',
      es: 'Noruega',
      fr: 'Norvège',
      en: 'Norway',
      tr: 'Norway',
    },
    latitude: '62.00000000',
    longitude: '10.00000000',
  },
  {
    id: 166,
    translations: {
      de: 'Oman',
      es: 'Omán',
      fr: 'Oman',
      en: 'Oman',
      tr: 'Oman',
    },
    latitude: '21.00000000',
    longitude: '57.00000000',
  },
  {
    id: 167,
    translations: {
      de: 'Pakistan',
      es: 'Pakistán',
      fr: 'Pakistan',
      en: 'Pakistan',
      tr: 'Pakistan',
    },
    latitude: '30.00000000',
    longitude: '70.00000000',
  },
  {
    id: 168,
    translations: {
      de: 'Palau',
      es: 'Palau',
      fr: 'Palaos',
      en: 'Palau',
      tr: 'Palau',
    },
    latitude: '7.50000000',
    longitude: '134.50000000',
  },
  {
    id: 169,
    translations: {
      de: 'Palästina',
      es: 'Palestina',
      fr: 'Palestine',
      en: 'Palestinian Territory Occupied',
      tr: 'Palestinian Territory Occupied',
    },
    latitude: '31.90000000',
    longitude: '35.20000000',
  },
  {
    id: 170,
    translations: {
      de: 'Panama',
      es: 'Panamá',
      fr: 'Panama',
      en: 'Panama',
      tr: 'Panama',
    },
    latitude: '9.00000000',
    longitude: '-80.00000000',
  },
  {
    id: 171,
    translations: {
      de: 'Papua-Neuguinea',
      es: 'Papúa Nueva Guinea',
      fr: 'Papouasie-Nouvelle-Guinée',
      en: 'Papua new Guinea',
      tr: 'Papua new Guinea',
    },
    latitude: '-6.00000000',
    longitude: '147.00000000',
  },
  {
    id: 172,
    translations: {
      de: 'Paraguay',
      es: 'Paraguay',
      fr: 'Paraguay',
      en: 'Paraguay',
      tr: 'Paraguay',
    },
    latitude: '-23.00000000',
    longitude: '-58.00000000',
  },
  {
    id: 173,
    translations: {
      de: 'Peru',
      es: 'Perú',
      fr: 'Pérou',
      en: 'Peru',
      tr: 'Peru',
    },
    latitude: '-10.00000000',
    longitude: '-76.00000000',
  },
  {
    id: 174,
    translations: {
      de: 'Philippinen',
      es: 'Filipinas',
      fr: 'Philippines',
      en: 'Philippines',
      tr: 'Philippines',
    },
    latitude: '13.00000000',
    longitude: '122.00000000',
  },
  {
    id: 175,
    translations: {
      de: 'Pitcairn',
      es: 'Islas Pitcairn',
      fr: 'Îles Pitcairn',
      en: 'Pitcairn Island',
      tr: 'Pitcairn Island',
    },
    latitude: '-25.06666666',
    longitude: '-130.10000000',
  },
  {
    id: 176,
    translations: {
      de: 'Polen',
      es: 'Polonia',
      fr: 'Pologne',
      en: 'Poland',
      tr: 'Poland',
    },
    latitude: '52.00000000',
    longitude: '20.00000000',
  },
  {
    id: 177,
    translations: {
      de: 'Portugal',
      es: 'Portugal',
      fr: 'Portugal',
      en: 'Portugal',
      tr: 'Portugal',
    },
    latitude: '39.50000000',
    longitude: '-8.00000000',
  },
  {
    id: 178,
    translations: {
      de: 'Puerto Rico',
      es: 'Puerto Rico',
      fr: 'Porto Rico',
      en: 'Puerto Rico',
      tr: 'Puerto Rico',
    },
    latitude: '18.25000000',
    longitude: '-66.50000000',
  },
  {
    id: 179,
    translations: {
      de: 'Katar',
      es: 'Catar',
      fr: 'Qatar',
      en: 'Qatar',
      tr: 'Qatar',
    },
    latitude: '25.50000000',
    longitude: '51.25000000',
  },
  {
    id: 180,
    translations: {
      de: 'Réunion',
      es: 'Reunión',
      fr: 'Réunion',
      en: 'Reunion',
      tr: 'Reunion',
    },
    latitude: '-21.15000000',
    longitude: '55.50000000',
  },
  {
    id: 181,
    translations: {
      de: 'Rumänien',
      es: 'Rumania',
      fr: 'Roumanie',
      en: 'Romania',
      tr: 'Romania',
    },
    latitude: '46.00000000',
    longitude: '25.00000000',
  },
  {
    id: 182,
    translations: {
      de: 'Russland',
      es: 'Rusia',
      fr: 'Russie',
      en: 'Russia',
      tr: 'Russia',
    },
    latitude: '60.00000000',
    longitude: '100.00000000',
  },
  {
    id: 183,
    translations: {
      de: 'Ruanda',
      es: 'Ruanda',
      fr: 'Rwanda',
      en: 'Rwanda',
      tr: 'Rwanda',
    },
    latitude: '-2.00000000',
    longitude: '30.00000000',
  },
  {
    id: 184,
    translations: {
      de: 'Sankt Helena',
      es: 'Santa Helena',
      fr: 'Sainte-Hélène',
      en: 'Saint Helena',
      tr: 'Saint Helena',
    },
    latitude: '-15.95000000',
    longitude: '-5.70000000',
  },
  {
    id: 185,
    translations: {
      de: 'St. Kitts und Nevis',
      es: 'San Cristóbal y Nieves',
      fr: 'Saint-Christophe-et-Niévès',
      en: 'Saint Kitts And Nevis',
      tr: 'Saint Kitts And Nevis',
    },
    latitude: '17.33333333',
    longitude: '-62.75000000',
  },
  {
    id: 186,
    translations: {
      de: 'Saint Lucia',
      es: 'Santa Lucía',
      fr: 'Saint-Lucie',
      en: 'Saint Lucia',
      tr: 'Saint Lucia',
    },
    latitude: '13.88333333',
    longitude: '-60.96666666',
  },
  {
    id: 187,
    translations: {
      de: 'Saint-Pierre und Miquelon',
      es: 'San Pedro y Miquelón',
      fr: 'Saint-Pierre-et-Miquelon',
      en: 'Saint Pierre and Miquelon',
      tr: 'Saint Pierre and Miquelon',
    },
    latitude: '46.83333333',
    longitude: '-56.33333333',
  },
  {
    id: 188,
    translations: {
      de: 'Saint Vincent und die Grenadinen',
      es: 'San Vicente y Granadinas',
      fr: 'Saint-Vincent-et-les-Grenadines',
      en: 'Saint Vincent And The Grenadines',
      tr: 'Saint Vincent And The Grenadines',
    },
    latitude: '13.25000000',
    longitude: '-61.20000000',
  },
  {
    id: 189,
    translations: {
      de: 'Saint-Barthélemy',
      es: 'San Bartolomé',
      fr: 'Saint-Barthélemy',
      en: 'Saint-Barthelemy',
      tr: 'Saint-Barthelemy',
    },
    latitude: '18.50000000',
    longitude: '-63.41666666',
  },
  {
    id: 190,
    translations: {
      de: 'Saint Martin',
      es: 'Saint Martin',
      fr: 'Saint-Martin',
      en: 'Saint-Martin (French part)',
      tr: 'Saint-Martin (French part)',
    },
    latitude: '18.08333333',
    longitude: '-63.95000000',
  },
  {
    id: 191,
    translations: {
      de: 'Samoa',
      es: 'Samoa',
      fr: 'Samoa',
      en: 'Samoa',
      tr: 'Samoa',
    },
    latitude: '-13.58333333',
    longitude: '-172.33333333',
  },
  {
    id: 192,
    translations: {
      de: 'San Marino',
      es: 'San Marino',
      fr: 'Saint-Marin',
      en: 'San Marino',
      tr: 'San Marino',
    },
    latitude: '43.76666666',
    longitude: '12.41666666',
  },
  {
    id: 193,
    translations: {
      de: 'São Tomé und Príncipe',
      es: 'Santo Tomé y Príncipe',
      fr: 'Sao Tomé-et-Principe',
      en: 'Sao Tome and Principe',
      tr: 'Sao Tome and Principe',
    },
    latitude: '1.00000000',
    longitude: '7.00000000',
  },
  {
    id: 194,
    translations: {
      de: 'Saudi-Arabien',
      es: 'Arabia Saudí',
      fr: 'Arabie Saoudite',
      en: 'Saudi Arabia',
      tr: 'Saudi Arabia',
    },
    latitude: '25.00000000',
    longitude: '45.00000000',
  },
  {
    id: 195,
    translations: {
      de: 'Senegal',
      es: 'Senegal',
      fr: 'Sénégal',
      en: 'Senegal',
      tr: 'Senegal',
    },
    latitude: '14.00000000',
    longitude: '-14.00000000',
  },
  {
    id: 196,
    translations: {
      de: 'Serbien',
      es: 'Serbia',
      fr: 'Serbie',
      en: 'Serbia',
      tr: 'Serbia',
    },
    latitude: '44.00000000',
    longitude: '21.00000000',
  },
  {
    id: 197,
    translations: {
      de: 'Seychellen',
      es: 'Seychelles',
      fr: 'Seychelles',
      en: 'Seychelles',
      tr: 'Seychelles',
    },
    latitude: '-4.58333333',
    longitude: '55.66666666',
  },
  {
    id: 198,
    translations: {
      de: 'Sierra Leone',
      es: 'Sierra Leone',
      fr: 'Sierra Leone',
      en: 'Sierra Leone',
      tr: 'Sierra Leone',
    },
    latitude: '8.50000000',
    longitude: '-11.50000000',
  },
  {
    id: 199,
    translations: {
      de: 'Singapur',
      es: 'Singapur',
      fr: 'Singapour',
      en: 'Singapore',
      tr: 'Singapore',
    },
    latitude: '1.36666666',
    longitude: '103.80000000',
  },
  {
    id: 250,
    translations: {
      de: 'Sint Maarten (niederl. Teil)',
      fr: 'Saint Martin (partie néerlandaise)',
      en: 'Sint Maarten (Dutch part)',
      tr: 'Sint Maarten (Dutch part)',
    },
    latitude: '18.03333300',
    longitude: '-63.05000000',
  },
  {
    id: 200,
    translations: {
      de: 'Slowakei',
      es: 'República Eslovaca',
      fr: 'Slovaquie',
      en: 'Slovakia',
      tr: 'Slovakia',
    },
    latitude: '48.66666666',
    longitude: '19.50000000',
  },
  {
    id: 201,
    translations: {
      de: 'Slowenien',
      es: 'Eslovenia',
      fr: 'Slovénie',
      en: 'Slovenia',
      tr: 'Slovenia',
    },
    latitude: '46.11666666',
    longitude: '14.81666666',
  },
  {
    id: 202,
    translations: {
      de: 'Salomonen',
      es: 'Islas Salomón',
      fr: 'Îles Salomon',
      en: 'Solomon Islands',
      tr: 'Solomon Islands',
    },
    latitude: '-8.00000000',
    longitude: '159.00000000',
  },
  {
    id: 203,
    translations: {
      de: 'Somalia',
      es: 'Somalia',
      fr: 'Somalie',
      en: 'Somalia',
      tr: 'Somalia',
    },
    latitude: '10.00000000',
    longitude: '49.00000000',
  },
  {
    id: 204,
    translations: {
      de: 'Republik Südafrika',
      es: 'República de Sudáfrica',
      fr: 'Afrique du Sud',
      en: 'South Africa',
      tr: 'South Africa',
    },
    latitude: '-29.00000000',
    longitude: '24.00000000',
  },
  {
    id: 205,
    translations: {
      de: 'Südgeorgien und die Südlichen Sandwichinseln',
      es: 'Islas Georgias del Sur y Sandwich del Sur',
      fr: 'Géorgie du Sud-et-les Îles Sandwich du Sud',
      en: 'South Georgia',
      tr: 'South Georgia',
    },
    latitude: '-54.50000000',
    longitude: '-37.00000000',
  },
  {
    id: 206,
    translations: {
      de: 'Südsudan',
      es: 'Sudán del Sur',
      fr: 'Soudan du Sud',
      en: 'South Sudan',
      tr: 'South Sudan',
    },
    latitude: '7.00000000',
    longitude: '30.00000000',
  },
  {
    id: 207,
    translations: {
      de: 'Spanien',
      es: 'España',
      fr: 'Espagne',
      en: 'Spain',
      tr: 'Spain',
    },
    latitude: '40.00000000',
    longitude: '-4.00000000',
  },
  {
    id: 208,
    translations: {
      de: 'Sri Lanka',
      es: 'Sri Lanka',
      fr: 'Sri Lanka',
      en: 'Sri Lanka',
      tr: 'Sri Lanka',
    },
    latitude: '7.00000000',
    longitude: '81.00000000',
  },
  {
    id: 209,
    translations: {
      de: 'Sudan',
      es: 'Sudán',
      fr: 'Soudan',
      en: 'Sudan',
      tr: 'Sudan',
    },
    latitude: '15.00000000',
    longitude: '30.00000000',
  },
  {
    id: 210,
    translations: {
      de: 'Suriname',
      es: 'Surinam',
      fr: 'Surinam',
      en: 'Suriname',
      tr: 'Suriname',
    },
    latitude: '4.00000000',
    longitude: '-56.00000000',
  },
  {
    id: 211,
    translations: {
      de: 'Svalbard und Jan Mayen',
      es: 'Islas Svalbard y Jan Mayen',
      fr: 'Svalbard et Jan Mayen',
      en: 'Svalbard And Jan Mayen Islands',
      tr: 'Svalbard And Jan Mayen Islands',
    },
    latitude: '78.00000000',
    longitude: '20.00000000',
  },
  {
    id: 212,
    translations: {
      de: 'Swasiland',
      es: 'Suazilandia',
      fr: 'Swaziland',
      en: 'Swaziland',
      tr: 'Swaziland',
    },
    latitude: '-26.50000000',
    longitude: '31.50000000',
  },
  {
    id: 213,
    translations: {
      de: 'Schweden',
      es: 'Suecia',
      fr: 'Suède',
      en: 'Sweden',
      tr: 'Sweden',
    },
    latitude: '62.00000000',
    longitude: '15.00000000',
  },
  {
    id: 214,
    translations: {
      de: 'Schweiz',
      es: 'Suiza',
      fr: 'Suisse',
      en: 'Switzerland',
      tr: 'Switzerland',
    },
    latitude: '47.00000000',
    longitude: '8.00000000',
  },
  {
    id: 215,
    translations: {
      de: 'Syrien',
      es: 'Siria',
      fr: 'Syrie',
      en: 'Syria',
      tr: 'Syria',
    },
    latitude: '35.00000000',
    longitude: '38.00000000',
  },
  {
    id: 216,
    translations: {
      de: 'Taiwan',
      es: 'Taiwán',
      fr: 'Taïwan',
      en: 'Taiwan',
      tr: 'Taiwan',
    },
    latitude: '23.50000000',
    longitude: '121.00000000',
  },
  {
    id: 217,
    translations: {
      de: 'Tadschikistan',
      es: 'Tayikistán',
      fr: 'Tadjikistan',
      en: 'Tajikistan',
      tr: 'Tajikistan',
    },
    latitude: '39.00000000',
    longitude: '71.00000000',
  },
  {
    id: 218,
    translations: {
      de: 'Tansania',
      es: 'Tanzania',
      fr: 'Tanzanie',
      en: 'Tanzania',
      tr: 'Tanzania',
    },
    latitude: '-6.00000000',
    longitude: '35.00000000',
  },
  {
    id: 219,
    translations: {
      de: 'Thailand',
      es: 'Tailandia',
      fr: 'Thaïlande',
      en: 'Thailand',
      tr: 'Thailand',
    },
    latitude: '15.00000000',
    longitude: '100.00000000',
  },
  {
    id: 220,
    translations: {
      de: 'Togo',
      es: 'Togo',
      fr: 'Togo',
      en: 'Togo',
      tr: 'Togo',
    },
    latitude: '8.00000000',
    longitude: '1.16666666',
  },
  {
    id: 221,
    translations: {
      de: 'Tokelau',
      es: 'Islas Tokelau',
      fr: 'Tokelau',
      en: 'Tokelau',
      tr: 'Tokelau',
    },
    latitude: '-9.00000000',
    longitude: '-172.00000000',
  },
  {
    id: 222,
    translations: {
      de: 'Tonga',
      es: 'Tonga',
      fr: 'Tonga',
      en: 'Tonga',
      tr: 'Tonga',
    },
    latitude: '-20.00000000',
    longitude: '-175.00000000',
  },
  {
    id: 223,
    translations: {
      de: 'Trinidad und Tobago',
      es: 'Trinidad y Tobago',
      fr: 'Trinité et Tobago',
      en: 'Trinidad And Tobago',
      tr: 'Trinidad And Tobago',
    },
    latitude: '11.00000000',
    longitude: '-61.00000000',
  },
  {
    id: 224,
    translations: {
      de: 'Tunesien',
      es: 'Túnez',
      fr: 'Tunisie',
      en: 'Tunisia',
      tr: 'Tunisia',
    },
    latitude: '34.00000000',
    longitude: '9.00000000',
  },
  {
    id: 225,
    translations: {
      de: 'Türkei',
      es: 'Turquía',
      fr: 'Turquie',
      en: 'Turkey',
      tr: 'Turkey',
    },
    latitude: '39.00000000',
    longitude: '35.00000000',
  },
  {
    id: 226,
    translations: {
      de: 'Turkmenistan',
      es: 'Turkmenistán',
      fr: 'Turkménistan',
      en: 'Turkmenistan',
      tr: 'Turkmenistan',
    },
    latitude: '40.00000000',
    longitude: '60.00000000',
  },
  {
    id: 227,
    translations: {
      de: 'Turks- und Caicosinseln',
      es: 'Islas Turks y Caicos',
      fr: 'Îles Turques-et-Caïques',
      en: 'Turks And Caicos Islands',
      tr: 'Turks And Caicos Islands',
    },
    latitude: '21.75000000',
    longitude: '-71.58333333',
  },
  {
    id: 228,
    translations: {
      de: 'Tuvalu',
      es: 'Tuvalu',
      fr: 'Tuvalu',
      en: 'Tuvalu',
      tr: 'Tuvalu',
    },
    latitude: '-8.00000000',
    longitude: '178.00000000',
  },
  {
    id: 229,
    translations: {
      de: 'Uganda',
      es: 'Uganda',
      fr: 'Uganda',
      en: 'Uganda',
      tr: 'Uganda',
    },
    latitude: '1.00000000',
    longitude: '32.00000000',
  },
  {
    id: 230,
    translations: {
      de: 'Ukraine',
      es: 'Ucrania',
      fr: 'Ukraine',
      en: 'Ukraine',
      tr: 'Ukraine',
    },
    latitude: '49.00000000',
    longitude: '32.00000000',
  },
  {
    id: 231,
    translations: {
      de: 'Vereinigte Arabische Emirate',
      es: 'Emiratos Árabes Unidos',
      fr: 'Émirats arabes unis',
      en: 'United Arab Emirates',
      tr: 'United Arab Emirates',
    },
    latitude: '24.00000000',
    longitude: '54.00000000',
  },
  {
    id: 232,
    translations: {
      de: 'Vereinigtes Königreich',
      es: 'Reino Unido',
      fr: 'Royaume-Uni',
      en: 'United Kingdom',
      tr: 'United Kingdom',
    },
    latitude: '54.00000000',
    longitude: '-2.00000000',
  },
  {
    id: 233,
    translations: {
      de: 'Vereinigte Staaten von Amerika',
      es: 'Estados Unidos',
      fr: 'États-Unis',
      en: 'United States',
      tr: 'United States',
    },
    latitude: '38.00000000',
    longitude: '-97.00000000',
  },
  {
    id: 234,
    translations: {
      de: 'Kleinere Inselbesitzungen der Vereinigten Staaten',
      es: 'Islas Ultramarinas Menores de Estados Unidos',
      fr: 'Îles mineures éloignées des États-Unis',
      en: 'United States Minor Outlying Islands',
      tr: 'United States Minor Outlying Islands',
    },
    latitude: '0.00000000',
    longitude: '0.00000000',
  },
  {
    id: 235,
    translations: {
      de: 'Uruguay',
      es: 'Uruguay',
      fr: 'Uruguay',
      en: 'Uruguay',
      tr: 'Uruguay',
    },
    latitude: '-33.00000000',
    longitude: '-56.00000000',
  },
  {
    id: 236,
    translations: {
      de: 'Usbekistan',
      es: 'Uzbekistán',
      fr: 'Ouzbékistan',
      en: 'Uzbekistan',
      tr: 'Uzbekistan',
    },
    latitude: '41.00000000',
    longitude: '64.00000000',
  },
  {
    id: 237,
    translations: {
      de: 'Vanuatu',
      es: 'Vanuatu',
      fr: 'Vanuatu',
      en: 'Vanuatu',
      tr: 'Vanuatu',
    },
    latitude: '-16.00000000',
    longitude: '167.00000000',
  },
  {
    id: 238,
    translations: {
      de: 'Heiliger Stuhl',
      es: 'Santa Sede',
      fr: 'voir Saint',
      en: 'Vatican City State (Holy See)',
      tr: 'Vatican City State (Holy See)',
    },
    latitude: '41.90000000',
    longitude: '12.45000000',
  },
  {
    id: 239,
    translations: {
      de: 'Venezuela',
      es: 'Venezuela',
      fr: 'Venezuela',
      en: 'Venezuela',
      tr: 'Venezuela',
    },
    latitude: '8.00000000',
    longitude: '-66.00000000',
  },
  {
    id: 240,
    translations: {
      de: 'Vietnam',
      es: 'Vietnam',
      fr: 'Viêt Nam',
      en: 'Vietnam',
      tr: 'Vietnam',
    },
    latitude: '16.16666666',
    longitude: '107.83333333',
  },
  {
    id: 241,
    translations: {
      de: 'Britische Jungferninseln',
      es: 'Islas Vírgenes del Reino Unido',
      fr: 'Îles Vierges britanniques',
      en: 'Virgin Islands (British)',
      tr: 'Virgin Islands (British)',
    },
    latitude: '18.43138300',
    longitude: '-64.62305000',
  },
  {
    id: 242,
    translations: {
      de: 'Amerikanische Jungferninseln',
      es: 'Islas Vírgenes de los Estados Unidos',
      fr: 'Îles Vierges des États-Unis',
      en: 'Virgin Islands (US)',
      tr: 'Virgin Islands (US)',
    },
    latitude: '18.34000000',
    longitude: '-64.93000000',
  },
  {
    id: 243,
    translations: {
      de: 'Wallis und Futuna',
      es: 'Wallis y Futuna',
      fr: 'Wallis-et-Futuna',
      en: 'Wallis And Futuna Islands',
      tr: 'Wallis And Futuna Islands',
    },
    latitude: '-13.30000000',
    longitude: '-176.20000000',
  },
  {
    id: 244,
    translations: {
      de: 'Westsahara',
      es: 'Sahara Occidental',
      fr: 'Sahara Occidental',
      en: 'Western Sahara',
      tr: 'Western Sahara',
    },
    latitude: '24.50000000',
    longitude: '-13.00000000',
  },
  {
    id: 245,
    translations: {
      de: 'Jemen',
      es: 'Yemen',
      fr: 'Yémen',
      en: 'Yemen',
      tr: 'Yemen',
    },
    latitude: '15.00000000',
    longitude: '48.00000000',
  },
  {
    id: 246,
    translations: {
      de: 'Sambia',
      es: 'Zambia',
      fr: 'Zambie',
      en: 'Zambia',
      tr: 'Zambia',
    },
    latitude: '-15.00000000',
    longitude: '30.00000000',
  },
  {
    id: 247,
    translations: {
      de: 'Simbabwe',
      es: 'Zimbabue',
      fr: 'Zimbabwe',
      en: 'Zimbabwe',
      tr: 'Zimbabwe',
    },
    latitude: '-20.00000000',
    longitude: '30.00000000',
  },
];
 */
