import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { dir } from 'i18next';
import { LocaleType, availableLocales } from '@/i18n/settings';
import { CollapsibleNavbar } from '@/components/layout/navbar';
import { Suspense } from 'react';
import { LoadingSpinner } from '@/components/shared/loading-spinner';
import AdSense from '@/components/shared/ads';
import './globals.css';

import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export type SharedPageProps = {
  params: { locale: LocaleType };
  searchParams?: { [key: string]: string | string[] | undefined };
};

const inter = Inter({ subsets: ['latin'] });
type LocaleRouteLayout = SharedPageProps & {
  children: React.ReactNode;
};

export default function RootLayout(props: LocaleRouteLayout) {
  const { params, children } = props;
  return (
    <html lang={params.locale} dir={dir(params.locale)} className="scroll-smooth">
      <meta name="google-adsense-account" content="ca-pub-9880416599476522"></meta>

      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-KCYH24DV1Q"></Script>
      <Script
        src={`window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-KCYH24DV1Q');`}
      ></Script>
      <body className={inter.className}>
        <AdSense />
        <CollapsibleNavbar />
        <Suspense fallback={<LoadingSpinner />}>{children}</Suspense>
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  // generates default paths for each locale domain/locale1, domain/locale2, etc.
  return availableLocales.map((lng) => ({ lng }));
}
