import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { dir } from 'i18next';
import { LocaleType, availableLocales } from '@/i18n/settings';
import { CollapsibleNavbar } from '@/components/layout/navbar';
import { Suspense } from 'react';
import { LoadingSpinner } from '@/components/shared/loading-spinner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export type SharedPageProps = {
  params: { locale: LocaleType };
};
const inter = Inter({ subsets: ['latin'] });
type LocaleRouteLayout = SharedPageProps & {
  children: React.ReactNode;
};

export default function RootLayout(props: LocaleRouteLayout) {
  const { params, children } = props;
  return (
    <html lang={params.locale} dir={dir(params.locale)}>
      <body className={inter.className}>
        <CollapsibleNavbar />
        <Suspense fallback={<LoadingSpinner />}>{children}</Suspense>
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  // generates default paths for each locale domain/locale1, domain/locale2, etc.
  return availableLocales.map((lng) => ({ lng }));
}
