export const questions = {
  en: [
    'Which gender(s) are you romantically attracted to?',
    'Which gender(s) are you sexually attracted to?',
    'How do you identify your gender?',
    'What gender(s) have you had relationships with in the past?',
    'What gender(s) do you want to have relationships with in the future?',
    'What gender(s) appear in your fantasies?',
    'Which gender do you feel more comfortable forming emotional bonds with?',
    'Can you have a romantic relationship without sexual attraction?',
    'Is your gender identity aligned with the sex assigned to you at birth?',
    'Do you feel attraction to multiple genders equally or does it fluctuate?',
    'Have you ever felt differently about your sexual attraction depending on the person rather than their gender?',
    'Do you feel your romantic attraction is stronger, weaker, or the same compared to your sexual attraction?',
  ],
  tr: [
    'Hangi cinsiyete romantik olarak çekiliyorsunuz?',
    'Hangi cinsiyete cinsel olarak çekiliyorsunuz?',
    'Kendinizi hangi cinsiyet ile tanımlıyorsunuz?',
    'Geçmişte hangi cinsiyetlerle ilişki yaşadınız?',
    'Gelecekte hangi cinsiyetlerle ilişki yaşamak istersiniz?',
    'Fantezilerinizde genellikle hangi cinsiyet(ler) yer alıyor?',
    'Duygusal bağ kurma konusunda hangi cinsiyetle daha rahat hissediyorsunuz?',
    'Cinsel çekim hissetmeden romantik ilişki yaşayabilir misiniz?',
    'Cinsiyet kimliğiniz doğumda size atanan cinsiyetle uyumlu mu?',
    'Birden fazla cinsiyete çekim hissediyor musunuz, yoksa bu değişken mi?',
    'Romantik çekiminiz, cinsel çekiminize kıyasla daha güçlü mü, daha zayıf mı, yoksa aynı mı hissediyorsunuz?',
  ],
  de: [
    'Zu welchem Geschlecht fühlen Sie sich romantisch hingezogen?',
    'Zu welchem Geschlecht fühlen Sie sich sexuell hingezogen?',
    'Mit welchem Geschlecht identifizieren Sie sich?',
    'Mit welchem Geschlecht hatten Sie in der Vergangenheit Beziehungen?',
    'Mit welchem Geschlecht möchten Sie in Zukunft Beziehungen haben?',
    'Welches Geschlecht kommt häufig in Ihren Fantasien vor?',
    'Mit welchem Geschlecht fühlen Sie sich emotional verbundener?',
    'Können Sie eine romantische Beziehung ohne sexuelle Anziehung führen?',
    'Stimmt Ihre Geschlechtsidentität mit dem bei der Geburt zugewiesenen Geschlecht überein?',
    'Empfinden Sie Anziehung für mehrere Geschlechter gleich oder schwankt es?',
    'Fühlen Sie, dass Ihre romantische Anziehung stärker, schwächer oder gleich im Vergleich zu Ihrer sexuellen Anziehung ist?',
  ],
};

export const options = {
  en: [
    [
      { value: 'women', label: 'Women' },
      { value: 'men', label: 'Men' },
      { value: 'both', label: 'Both' },
      { value: 'neither', label: 'Neither' },
    ],
    [
      { value: 'women', label: 'Women' },
      { value: 'men', label: 'Men' },
      { value: 'both', label: 'Both' },
      { value: 'neither', label: 'Neither' },
    ],
    [
      { value: 'woman', label: 'Woman' },
      { value: 'man', label: 'Man' },
      { value: 'non-binary', label: 'Non-binary' },
      { value: 'other', label: 'Other' },
    ],
    [
      { value: 'only-women', label: 'Only women' },
      { value: 'only-men', label: 'Only men' },
      { value: 'both', label: 'Both' },
      { value: 'neither', label: 'Neither' },
    ],
    [
      { value: 'only-women', label: 'Only women' },
      { value: 'only-men', label: 'Only men' },
      { value: 'both', label: 'Both' },
      { value: 'neither', label: 'Neither' },
    ],
    [
      { value: 'mostly-women', label: 'Mostly women' },
      { value: 'mostly-men', label: 'Mostly men' },
      { value: 'both', label: 'Both' },
      { value: 'neither', label: 'Neither' },
    ],
    [
      { value: 'with-women', label: 'With women' },
      { value: 'with-men', label: 'With men' },
      { value: 'both', label: 'Both' },
      { value: 'gender-independent', label: 'Gender-independent' },
    ],
    [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      { value: 'sometimes', label: 'Sometimes' },
      { value: 'not-sure', label: 'Not sure' },
    ],
    [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      { value: 'not-sure', label: 'Not sure' },
    ],
    [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
      { value: 'sometimes', label: 'Sometimes' },
      { value: 'not-sure', label: 'Not sure' },
    ],
    [
      { value: 'always', label: 'Always' },
      { value: 'often', label: 'Often' },
      { value: 'rarely', label: 'Rarely' },
      { value: 'never', label: 'Never' },
    ],
    [
      { value: 'stronger', label: 'Stronger' },
      { value: 'weaker', label: 'Weaker' },
      { value: 'same', label: 'Same' },
    ],
  ],
  tr: [
    [
      { value: 'women', label: 'Kadın' },
      { value: 'men', label: 'Erkek' },
      { value: 'both', label: 'Her ikisi de' },
      { value: 'neither', label: 'Hiçbiri' },
    ],
    [
      { value: 'women', label: 'Kadın' },
      { value: 'men', label: 'Erkek' },
      { value: 'both', label: 'Her ikisi de' },
      { value: 'neither', label: 'Hiçbiri' },
    ],
    [
      { value: 'woman', label: 'Kadın' },
      { value: 'man', label: 'Erkek' },
      { value: 'non-binary', label: 'Non-binary' },
      { value: 'other', label: 'Diğer' },
    ],
    [
      { value: 'only-women', label: 'Sadece kadınlar' },
      { value: 'only-men', label: 'Sadece erkekler' },
      { value: 'both', label: 'Her ikisi de' },
      { value: 'neither', label: 'Hiçbiri' },
    ],
    [
      { value: 'only-women', label: 'Sadece kadınlar' },
      { value: 'only-men', label: 'Sadece erkekler' },
      { value: 'both', label: 'Her ikisi de' },
      { value: 'neither', label: 'Hiçbiri' },
    ],
    [
      { value: 'mostly-women', label: 'Genellikle kadınlar' },
      { value: 'mostly-men', label: 'Genellikle erkekler' },
      { value: 'both', label: 'Her ikisi de' },
      { value: 'neither', label: 'Hiçbiri' },
    ],
    [
      { value: 'with-women', label: 'Kadınlarla' },
      { value: 'with-men', label: 'Erkeklerle' },
      { value: 'both', label: 'Her ikisiyle de' },
      { value: 'gender-independent', label: 'Cinsiyete bağlı değil' },
    ],
    [
      { value: 'yes', label: 'Evet' },
      { value: 'no', label: 'Hayır' },
      { value: 'sometimes', label: 'Bazen' },
      { value: 'not-sure', label: 'Emin değilim' },
    ],
    [
      { value: 'yes', label: 'Evet' },
      { value: 'no', label: 'Hayır' },
      { value: 'not-sure', label: 'Emin değilim' },
    ],
    [
      { value: 'yes', label: 'Evet' },
      { value: 'no', label: 'Hayır' },
      { value: 'sometimes', label: 'Bazen' },
      { value: 'not-sure', label: 'Emin değilim' },
    ],
    [
      { value: 'always', label: 'Her zaman' },
      { value: 'often', label: 'Sık sık' },
      { value: 'rarely', label: 'Nadiren' },
      { value: 'never', label: 'Asla' },
    ],
    [
      { value: 'stronger', label: 'Daha güçlü' },
      { value: 'weaker', label: 'Daha zayıf' },
      { value: 'same', label: 'Aynı' },
    ],
  ],
  de: [
    [
      { value: 'women', label: 'Frauen' },
      { value: 'men', label: 'Männer' },
      { value: 'both', label: 'Beide' },
      { value: 'neither', label: 'Keine' },
    ],
    [
      { value: 'women', label: 'Frauen' },
      { value: 'men', label: 'Männer' },
      { value: 'both', label: 'Beide' },
      { value: 'neither', label: 'Keine' },
    ],
    [
      { value: 'woman', label: 'Frau' },
      { value: 'man', label: 'Mann' },
      { value: 'non-binary', label: 'Nicht-binär' },
      { value: 'other', label: 'Andere' },
    ],
    [
      { value: 'only-women', label: 'Nur Frauen' },
      { value: 'only-men', label: 'Nur Männer' },
      { value: 'both', label: 'Beide' },
      { value: 'neither', label: 'Keine' },
    ],
    [
      { value: 'only-women', label: 'Nur Frauen' },
      { value: 'only-men', label: 'Nur Männer' },
      { value: 'both', label: 'Beide' },
      { value: 'neither', label: 'Keine' },
    ],
    [
      { value: 'mostly-women', label: 'Hauptsächlich Frauen' },
      { value: 'mostly-men', label: 'Hauptsächlich Männer' },
      { value: 'both', label: 'Beide' },
      { value: 'neither', label: 'Keine' },
    ],
    [
      { value: 'with-women', label: 'Mit Frauen' },
      { value: 'with-men', label: 'Mit Männern' },
      { value: 'both', label: 'Beide' },
      { value: 'gender-independent', label: 'Geschlechtsunabhängig' },
    ],
    [
      { value: 'yes', label: 'Ja' },
      { value: 'no', label: 'Nein' },
      { value: 'sometimes', label: 'Manchmal' },
      { value: 'not-sure', label: 'Nicht sicher' },
    ],
    [
      { value: 'yes', label: 'Ja' },
      { value: 'no', label: 'Nein' },
      { value: 'not-sure', label: 'Nicht sicher' },
    ],
    [
      { value: 'yes', label: 'Ja' },
      { value: 'no', label: 'Nein' },
      { value: 'sometimes', label: 'Manchmal' },
      { value: 'not-sure', label: 'Nicht sicher' },
    ],
    [
      { value: 'always', label: 'Immer' },
      { value: 'often', label: 'Oft' },
      { value: 'rarely', label: 'Selten' },
      { value: 'never', label: 'Nie' },
    ],
    [
      { value: 'stronger', label: 'Stärker' },
      { value: 'weaker', label: 'Schwächer' },
      { value: 'same', label: 'Gleich' },
    ],
  ],
};
export const orientations = {
  en: [
    { name: 'Heterosexual', description: 'Attracted to the opposite gender.', score: 0 },
    { name: 'Homosexual', description: 'Attracted to the same gender.', score: 0 },
    { name: 'Bisexual', description: 'Attracted to both genders.', score: 0 },
    { name: 'Pansexual', description: 'Attracted regardless of gender identity or biological sex.', score: 0 },
    { name: 'Asexual', description: 'Experiences little or no sexual attraction.', score: 0 },
  ],
  tr: [
    { name: 'Heteroseksüel', description: 'Karşı cinse romantik ve/veya cinsel çekim duyan.', score: 0 },
    { name: 'Eşcinsel', description: 'Aynı cinse romantik ve/veya cinsel çekim duyan.', score: 0 },
    {
      name: 'Biseksüel',
      description: 'Hem kendi cinsine hem de karşı cinse romantik ve/veya cinsel çekim duyan.',
      score: 0,
    },
    {
      name: 'Panseksüel',
      description:
        'Cinsiyet kimliği veya biyolojik cinsiyete bakılmaksızın herhangi birine romantik ve/veya cinsel çekim duyan.',
      score: 0,
    },
    { name: 'Aseksüel', description: 'Cinsel çekim hissetmeyen veya çok az hisseden.', score: 0 },
  ],
  de: [
    { name: 'Heterosexuell', description: 'Romantische und/oder sexuelle Anziehung zum anderen Geschlecht.', score: 0 },
    { name: 'Homosexuell', description: 'Romantische und/oder sexuelle Anziehung zum gleichen Geschlecht.', score: 0 },
    { name: 'Bisexuell', description: 'Romantische und/oder sexuelle Anziehung zu beiden Geschlechtern.', score: 0 },
    {
      name: 'Pansexuell',
      description:
        'Romantische und/oder sexuelle Anziehung unabhängig von Geschlechtsidentität oder biologischem Geschlecht.',
      score: 0,
    },
    { name: 'Asexuell', description: 'Empfindet wenig bis keine sexuelle Anziehung.', score: 0 },
  ],
};
